### ISSUE TITLE
Prijedlog poveznice na pravu sliku u README.md

### ISSUE THREAD

**Issue by sbravar** [SolderedElectronics/Soldered-microSD-Card-Reader-Breakout-Arduino-Library#1]
https://github.com/SolderedElectronics/Soldered-microSD-Card-Reader-Breakout-Arduino-Library/blob/792f7f2d7069ef15a084f238b3482d81fe6dba92/README.md?plain=1#L6

umjesto:

https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg

čini mi se da bi moglo biti:

https://github.com/SolderedElectronics/MicroSD-breakout-hardware-design/blob/main/OUTPUTS/V1.0.0/333050.jpg?raw=true

**Comment by rsoric** [comment]
Hello, and thank you for your feedback. We are currently working on automating this process. Soon, all repositories will be updated with the real content. Cheers!
